name: WEREWOLF
main: com.genpyon.Main
version: 1.0.0
author: Genpyon
commands:
    ww:
       permission: werewolf.ww
    s:
       permission: werewolf.s
    c:
       permission: werewolf.c
    check:
       permission: werewolf.check
    shop:
       permission: werewolf.shop
permissions:
    werewolf.*:
       default: op
    werewolf.ww:
       default: op
    werewolf.s:
       default: true
    werewolf.shop:
       default: true
    werewolf.c:
       default: true
    werewolf.check:
       default: true
