name: WEREWOLF
main: com.genpyon.Main
version: 1.0.0
author: Genpyon
commands:
    ww:
       description: main command
       permission: werewolf.ww
permissions:
    werewolf.*:
       description: LastManStanding no Command dayo
       default: op
    werewolf.ww:
       description: LastManStanding no Command dayo
       default: op
